name: 'test'
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SECRETFORBUG }}
        run: |
          echo "$SUPER_SECRET" > /tmp/secret.txt
